### ISSUE TITLE
file patched - no differences from original

### ISSUE THREAD

**Issue by dzanonuniv** [fabianosrc/TermsrvPatcher#1]
Hi,
I'm trying to patch a Windows 7 Pro SP1 x64 machine, but "fc" says that there are no diffrences.
I noticed that the output of Get-FullOSBuildNumber for my machine is 7601.24546 which
differs from the build number you put in the script, maybe that's the problem?
Thanks

**Comment by fabianosrc** [comment]
Hello, thanks for your contribution. I will fix

**Comment by dzanonuniv** [comment]
I will keep a machine for testing purpose, I'm not good at programming but I can help with testing.
Thanks

**Comment by fabianosrc** [comment]
@dzanonuniv please, could you submit your termsrv.dll file? Look in C:\Windows\System32\termsrv.dll

**Comment by dzanonuniv** [comment]
Here:
https://we.tl/t-39pUm2NIjq

**Comment by fabianosrc** [comment]
@dzanonuniv try again. I'm still working on this script to make it more dynamic with regex pattern

**Comment by dzanonuniv** [comment]
Same output, "fc" finds no differences and if I try to rdp on the same machine with two users it asks me to log out.

**Comment by fabianosrc** [comment]
Oops, I made a mistake, leave some unused code in this script. It's fixed

**Comment by doandat943** [comment]
wow, can i have your patched "termsrv.dll" @dzanonuniv
