### ISSUE TITLE
not working on lastest Windows 10 update

### ISSUE THREAD

**Issue by doandat943** [fabianosrc/TermsrvPatcher#2]
my specs:
![image](https://github.com/fabianosrc/TermsrvPatcher/assets/113295259/160242dd-760a-4d81-9d90-cc172253d286)

original and patched termsrv.dll file:
http://joverse.me:2000/TEMP/termsrv.dll.zip

The patch seems to have stopped working since the May update,
![image](https://github.com/fabianosrc/TermsrvPatcher/assets/113295259/44fbc650-5ed0-48a9-b6e6-4e1c7fb0b1d0)

hope you can check out

**Comment by doandat943** [comment]
![image](https://github.com/fabianosrc/TermsrvPatcher/assets/113295259/2340dd57-2834-40c5-b73c-e7676692b601)
im just check sha32, i think tool it not really patch.  #1

**Comment by doandat943** [comment]
![image](https://github.com/fabianosrc/TermsrvPatcher/assets/113295259/63325316-c39e-4df2-b795-740f58a6da80)

**Comment by fabianosrc** [comment]
Hello @doandat943, thanks for reporting this, I'll fix it.

**Comment by fabianosrc** [comment]
@doandat943 please try again.

**Comment by doandat943** [comment]
thank you very much, so helpful, it working like a charm
