### ISSUE TITLE
Grant full control on the termsrv.dll file

### ISSUE THREAD

**Issue by leleb** [fabianosrc/TermsrvPatcher#3]
Currently logged in user could be different from the current console user (I am using a rmm terminal logged in as a system user, not the desktop logged user)
I suggest to modify:
`$currentUserName = (Get-WmiObject -Class Win32_ComputerSystem).UserName`
into
`$currentUserName = whoami`

**Comment by fabianosrc** [comment]
Thank you. I will be implementing these improvements
