### ISSUE TITLE
Pattern missing I am on latest version of Windows 11 23H2

### ISSUE THREAD

**Issue by bolavefasfas** [fabianosrc/TermsrvPatcher#5]
![image](https://github.com/fabianosrc/TermsrvPatcher/assets/82230241/0b810253-0daf-42bd-b9d5-73b0d6ae30b6)
This is my windows version 
---

I Tried https://woshub.com/how-to-allow-multiple-rdp-sessions-in-windows-10/ this guide and coudnt find text to find to be replaced by as my windows version is new

---

even in this https://github.com/sebaxakerhtc/rdpwrap.ini?tab=readme-ov-file
![image](https://github.com/fabianosrc/TermsrvPatcher/assets/82230241/6e1ab003-ee77-4b90-b926-a537e09fcd89)

The version I am windows isnt their

---

I tried everything can you update the script to get updated pattern

When i runu the script it says pattern not found.
Thanks wating for update.

**Comment by fabianosrc** [comment]
Hello @bolavefasfas. I will be checking and updating this script. Please wait.

**Comment by bolavefasfas** [comment]
> Hello @bolavefasfas. I will be checking and updating this script. Please wait.

Thanks am wating for your reply and update 

I found this https://www.mysysadmintips.com/windows/clients/998-multiple-rdp-remote-desktop-sessions-in-windows-11

This has 23H2 and has a diffrent build version 

Can you tell me how to know what string to find in the version any version ?
like if a update is pushed I can find it myself if possible ?

**Comment by fabianosrc** [comment]
I'll try to create a pattern match via regex to make it easier in case of a future Windows update

**Comment by bolavefasfas** [comment]
Refrence link
https://it-advisor.ru/forum/obsuzhdenie-statej/976-terminalnyj-server-iz-windows-11.html

<img width="763" alt="image" src="https://github.com/fabianosrc/TermsrvPatcher/assets/82230241/96c9b23d-0fa8-481b-9354-219ded0141da">

after hours of search found it on this forum 
tried using 3-4 hex editors coudnt edit my orignal file idk 
Wating for you to push update 

**termsrv.dll 10.0.22621.2861** **This is my version** 

Find:
`39 81 3C 06 00 00 0F 84 DF 89 01 00`
Replaced by:
`B8 00 01 00 00 89 81 38 06 00 00 90`

**termsrv.dll 10.0.22621.3085** 

Find:
`39 81 3C 06 00 00 0F 84 6F 8C 01 00`
Replaced by:
`B8 00 01 00 00 89 81 38 06 00 00 90`

Found the codes for newer version also can you add this too ?

**Comment by fabianosrc** [comment]
Thank you! I use EmEditor for find hex code. Works fine!

**Comment by fabianosrc** [comment]
Hi, a fixed some bugs, please try again

**Comment by bolavefasfas** [comment]
The update you pushed is working.

**Comment by fabianosrc** [comment]
@bolavefasfas, check if your Windows user accounts are authorized for remote login.

Press Win + R and then input "sysdm.cpl" and then hit "OK".

Click on the "Remote" tab

![image](https://github.com/fabianosrc/TermsrvPatcher/assets/78154525/2db0a4d7-8636-493f-8b44-923e1bd549cb)

**Comment by bolavefasfas** [comment]
Did this already have added every user their was in the list and added Everyone user also.
even after doing this I am unable to connect to users within same pc but an able to with other devices.
Thats why I was confused and asked.
