### ISSUE TITLE
No longer work in windows 11 last update

### ISSUE THREAD

**Issue by ehsanwwe** [fabianosrc/TermsrvPatcher#6]
hi guys
i test it in 2 PCs  from last week
i has been trouble with multiple remote desktop after last week Microsoft update

Windows 11 pro
Version : 10.0.22631 
build :22631

**Comment by fabianosrc** [comment]
Hi, thanks for reporting this bug, I will fix it.

--
Fabiano Silva
________________________________
From: Ehsan Moradi ***@***.***>
Sent: Tuesday, August 6, 2024 3:38 AM
To: fabianosrc/TermsrvPatcher ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fabianosrc/TermsrvPatcher] No longer work in windows 11 last update (Issue #6)


hi guys
i test it in 2 PCs from last week
i has been trouble with multiple remote desktop after last week Microsoft update

Windows 11 pro
Version : 10.0.22631
build :22631

**Comment by AlimFreight** [comment]
Hey @fabianosrc , any news about the fix?

**Comment by fabianosrc** [comment]
Hi guys. Sorry but I'm still trying to identify where the problem is. I ran on a Windows 11 23H2 22631.4037 and it works fine

**Comment by fabianosrc** [comment]
You may need to run the script again after windows updates, as the update may overwrite the patched file.

**Comment by ehsanwwe** [comment]
Fabiano tnx , its work like a charm.

**Comment by AlimFreight** [comment]
I am getting this:
`PS C:\Users\Yan\Downloads> .\TermsrvPatcher.ps1
At C:\Users\Yan\Downloads\TermsrvPatcher.ps1:40 char:60
+ ... script type="application/json" id="client-env">{"locale":"en","featur ...
+                                                             ~~~~~
Unexpected token ':"en"' in expression or statement.
At C:\Users\Yan\Downloads\TermsrvPatcher.ps1:40 char:65
+ ... cript type="application/json" id="client-env">{"locale":"en","feature ...
+                                                                 ~
Missing argument in parameter list.
At C:\Users\Yan\Downloads\TermsrvPatcher.ps1:40 char:864
+ ... ite_metered_billing_update","ignore_hidden_in_quote_reply"]}</script>
+                                                                 ~
The '<' operator is reserved for future use.
At C:\Users\Yan\Downloads\TermsrvPatcher.ps1:251 char:84
+ ... tion/json" data-target="react-partial.embeddedData">{"props":{"docsUr ...
+                                                                 ~
Unexpected token ':' in expression or statement.
At C:\Users\Yan\Downloads\TermsrvPatcher.ps1:251 char:95
+ ... ":{"docsUrl":"https://docs.github.com/get-started/accessibility/keybo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token ':"https://docs.github.com/get-started/accessibility/keyboard-shortcuts"' in expression or statement.
At C:\Users\Yan\Downloads\TermsrvPatcher.ps1:251 char:168
+ ... s.github.com/get-started/accessibility/keyboard-shortcuts"}}</script>
+                                                                 ~
The '<' operator is reserved for future use.
At C:\Users\Yan\Downloads\TermsrvPatcher.ps1:275 char:254
+ ... ink Button--medium Button d-lg-none color-fg-inherit p-1">  <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\Users\Yan\Downloads\TermsrvPatcher.ps1:318 char:45
+             <ul class="list-style-none f5" >
+                                             ~
Missing file specification after redirection operator.
At C:\Users\Yan\Downloads\TermsrvPatcher.ps1:532 char:13
+       CI/CD &amp; Automation
+             ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\Yan\Downloads\TermsrvPatcher.ps1:656 char:45
+             <ul class="list-style-none f5" >
+                                             ~
Missing file specification after redirection operator.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken`

**Comment by fabianosrc** [comment]
@AlimFreight what's your PowerShell version?

**Comment by fabianosrc** [comment]
I'll be working on some improvements soon. I'm not very good at programming yet.

**Comment by AlimFreight** [comment]
> @AlimFreight what's your PowerShell version? and your OS version?
Version
-------
5.1.22621.1037
8m

OS Name:                   Microsoft Windows 11 Enterprise
OS Version:                10.0.22624 N/A Build 22624

**Comment by fabianosrc** [comment]
> > @AlimFreight what's your PowerShell version? and your OS version?
> > Version
> 
> 5.1.22621.1037 8m
> 
> OS Name: Microsoft Windows 11 Enterprise OS Version: 10.0.22624 N/A Build 22624

Please wait. I need to check a few things.

**Comment by fabianosrc** [comment]
@AlimFreight look at this: https://youtu.be/K_NWM-fRkPQ

**Comment by AlimFreight** [comment]
Thank you so much; the script works perfectly! The issue was with the file structure, which somehow got corrupted during downloading.
